name: Extract and Organize IMG Files from URL

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "Paste the direct link to the ZIP file containing IMG files"
        required: true
      repo_url:
        description: "Paste the GitHub repository link where files should be uploaded"
        required: true

jobs:
  extract-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip tar p7zip-full android-sdk-libsparse-utils e2fsprogs mount

      - name: Download and Extract ZIP File
        run: |
          set -e
          mkdir -p extracted_files
          echo "Downloading ZIP file from: ${{ github.event.inputs.zip_url }}"
          wget -O archive.zip "${{ github.event.inputs.zip_url }}" || { echo "Failed to download ZIP file"; exit 1; }
          unzip -o archive.zip -d extracted_files/

      - name: Organize and Extract IMG Files
        run: |
          set -e
          mkdir -p organized_files
          cd extracted_files || exit 1

          for img in *.img; do
            if [ -f "$img" ]; then
              folder_name="${img%.*}"
              mkdir -p "../organized_files/$folder_name"
              mv "$img" "../organized_files/$folder_name/"
              
              cd "../organized_files/$folder_name"

              echo "Processing: $img"
              
              fs_type=$(file "$img")
              echo "File Type: $fs_type"

              echo "Trying 7z extraction..."
              7z x "$img" -oextracted || echo "7z extraction failed for $img"

              if echo "$fs_type" | grep -q "Android sparse image"; then
                echo "Converting sparse image: $img"
                if simg2img "$img" raw.img; then
                  mv raw.img "$img"
                else
                  echo "simg2img failed for $img"
                fi
              fi

              if echo "$fs_type" | grep -q "ext4"; then
                echo "Extracting ext4 image: $img"
                mkdir -p extracted
                if sudo mount -o loop "$img" extracted; then
                  echo "Mounted successfully, copying files..."
                  cp -r extracted/* extracted/ || echo "Copy failed"
                  sudo umount extracted
                else
                  echo "Mount failed, trying debugfs..."
                  debugfs "$img" -R "dump -p / extracted/" || echo "debugfs failed for $img"
                fi
              fi

              cd ../../extracted_files || exit 1
            fi
          done

      - name: Clone Target Repository
        run: |
          repo_name=$(basename "${{ github.event.inputs.repo_url }}" .git)
          git clone "${{ github.event.inputs.repo_url }}" "$repo_name"
          echo "Cloned target repository: ${{ github.event.inputs.repo_url }}"

      - name: Copy Extracted Files to Target Repository
        run: |
          repo_name=$(basename "${{ github.event.inputs.repo_url }}" .git)
          cp -r organized_files/* "$repo_name/"
          cd "$repo_name"
          git add .
          git commit -m "Added extracted IMG files"
          git push "${{ github.event.inputs.repo_url }}" HEAD:main || echo "No changes to commit."
