name: PitchBlack [PBRP]

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'PBRP Manifest Branch'
        required: true
        default: 'android-12.1'
        type: choice
        options:
        - android-12.1
        - android-11.0
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/FusinX/android_device_realme_samurai'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'twrp_samurai-eng-99.87.36-SP2A.220405.004-12-test-keys'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recoveryimage'
        type: choice
        options:
        - pbrp
        - recoveryimage
    
jobs:
  build:
    name: Build PBRP by ${{ github.actor }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup build environment
      run: |
        sudo apt update && sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python3 libtinfo5 libstdc++6
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo mv ~/bin/repo /usr/bin/repo
    
    - name: Initialize repo & sync sources
      run: |
        mkdir -p android-recovery && cd android-recovery
        git config --global user.name "lazycodebuilder"
        git config --global user.email "154446636+lazycodebuilder@users.noreply.github.com"
        repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${{ inputs.MANIFEST_BRANCH }}
        repo sync -j$(nproc --all) --force-sync
    
    - name: Clone Device Tree
      run: |
        cd android-recovery/device
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} realme/samurai
    
    - name: Build Recovery
      run: |
        cd android-recovery
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_samurai-eng
        mka recoveryimage
    
    - name: Upload Recovery Artifact
      uses: actions/upload-artifact@v3
      with:
        name: recovery.img
        path: android-recovery/out/target/product/$(ls android-recovery/out/target/product)/recovery.img
