name: TeamWin [TWRP]

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Manifest Branch'
        required: true
        default: 'twrp-7.1'
        type: choice
        options:
        - twrp-7.1
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/FusinX/android_device_lenovo_brady-twrp'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'android-7.1'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y install gperf gcc-multilib g++-multilib libncurses5-dev zlib1g-dev \
          lib32z1-dev libssl-dev libxml2-utils bc ccache \
          python2 python-is-python2 unzip zip flex bison curl 
    
    - name: Install OpenJDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    
    - name: Install Git-Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
    
    - name: Initialize Repo
      run: |
        mkdir android-recovery
        cd android-recovery
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-7.1
    
    - name: Sync Source Code
      run: |
        cd android-recovery
        repo sync -j$(nproc --all) --force-sync
    
    - name: Clone Device Tree
      run: |
        cd android-recovery
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./device/lenovo/brady
    
    - name: Build TWRP Recovery
      run: |
        cd android-recovery
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_brady-eng
        make clean
        make ${{ inputs.BUILD_TARGET }}image -j$(nproc --all)
    
    - name: Upload Recovery Image
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-${{ inputs.BUILD_TARGET }}-Lenovo-Brady
        path: android-recovery/out/target/product/brady/${{ inputs.BUILD_TARGET }}.img
