name: TeamWin [TWRP]

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Manifest Branch'
        required: true
        default: 'twrp-8.1'
        type: choice
        options:
        - twrp-8.1
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/FusinX/android_device_lenovo_brady-twrp.git'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'twrp-8.0'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
      LDCHECK:
        description: 'Use LDCHECK'
        required: false
        default: 'true'
        type: boolean
      LDCHECKPATH:
        description: 'Path of blobs to check'
        required: true
        default: 'device/lenovo/brady/prebuilt/lib'

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y gperf gcc-multilib g++-multilib libncurses5-dev zlib1g-dev \
          lib32z1-dev libssl-dev libxml2-utils bc ccache \
          python2 python-is-python2 python3 python3-pip unzip zip flex bison curl

    - name: Install OpenJDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install Git-Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize Repo
      run: |
        mkdir android-recovery
        cd android-recovery
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b ${{ inputs.MANIFEST_BRANCH }}

    - name: Sync Source Code
      run: |
        cd android-recovery
        repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree (Authenticated)
      run: |
        cd android-recovery
        REPO_PATH=$(echo "${{ inputs.DEVICE_TREE }}" | sed 's|https://github.com/||')
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/$REPO_PATH -b ${{ inputs.DEVICE_TREE_BRANCH }} ./device/lenovo/brady

    - name: Set Build Target
      run: |
        if [ "${{ inputs.BUILD_TARGET }}" == "recovery" ]; then
          echo "BUILD_TARGET_NAME=recoveryimage" >> $GITHUB_ENV
          echo "BUILD_IMAGE_NAME=recovery" >> $GITHUB_ENV
        elif [ "${{ inputs.BUILD_TARGET }}" == "boot" ]; then
          echo "BUILD_TARGET_NAME=bootimage" >> $GITHUB_ENV
          echo "BUILD_IMAGE_NAME=boot" >> $GITHUB_ENV
        else
          echo "BUILD_TARGET_NAME=vendorbootimage" >> $GITHUB_ENV
          echo "BUILD_IMAGE_NAME=vendorboot" >> $GITHUB_ENV
        fi

    - name: Build TWRP
      run: |
        cd android-recovery
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        source build/envsetup.sh
        lunch omni_brady-eng
        make clean
        mka ${{ env.BUILD_TARGET_NAME }}

    - name: Run LDCheck
      if: inputs.LDCHECK == 'true'
      run: |
        cd android-recovery
        git clone https://github.com/TeamWin/android_external_ldcheck
        cd out/target/product/brady/recovery/root
        python3 ../../../android_external_ldcheck/ldcheck.py -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
        echo "✅ LDCheck complete."
      continue-on-error: true

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-${{ inputs.BUILD_TARGET }}-Lenovo-Brady
        path: android-recovery/out/target/product/brady/${{ env.BUILD_IMAGE_NAME }}.img
